
INSERT INTO VinylRecords (Title, Artist, Genre, ReleaseYear, Label, Condition, Price, Description) VALUES
('Abbey Road', 'The Beatles', 'Rock', 1969, 'Apple Records', 'Mint', 30.00, 'The eleventh studio album by the English rock band The Beatles.'),
('Thriller', 'Michael Jackson', 'Pop', 1982, 'Epic Records', 'Near Mint', 25.00, 'The sixth studio album by American singer Michael Jackson.'),
('Rumours', 'Fleetwood Mac', 'Rock', 1977, 'Warner Bros.', 'Very Good', 20.00, 'The eleventh studio album by British-American rock band Fleetwood Mac.'),
('The Dark Side of the Moon', 'Pink Floyd', 'Rock', 1973, 'Harvest Records', 'Mint', 35.00, 'The eighth studio album by English rock band Pink Floyd.'),
('Back in Black', 'AC/DC', 'Rock', 1980, 'Atlantic Records', 'Good', 15.00, 'The seventh studio album by Australian rock band AC/DC.'),
('Hotel California', 'Eagles', 'Rock', 1976, 'Asylum Records', 'Near Mint', 28.00, 'The fifth studio album by American rock band Eagles.'),
('Led Zeppelin IV', 'Led Zeppelin', 'Rock', 1971, 'Atlantic Records', 'Mint', 32.00, 'The fourth studio album by English rock band Led Zeppelin.'),
('Nevermind', 'Nirvana', 'Grunge', 1991, 'DGC Records', 'Very Good', 22.00, 'The second studio album by American rock band Nirvana.'),
('The Wall', 'Pink Floyd', 'Rock', 1979, 'Harvest Records', 'Good', 18.00, 'The eleventh studio album by English rock band Pink Floyd.'),
('Born to Run', 'Bruce Springsteen', 'Rock', 1975, 'Columbia Records', 'Mint', 27.00, 'The third studio album by American singer-songwriter Bruce Springsteen.'),
('Purple Rain', 'Prince', 'Pop', 1984, 'Warner Bros.', 'Near Mint', 24.00, 'The sixth studio album by American recording artist Prince.'),
('Sgt. Pepper''s Lonely Hearts Club Band', 'The Beatles', 'Rock', 1967, 'Parlophone', 'Mint', 33.00, 'The eighth studio album by the English rock band The Beatles.'),
('The Joshua Tree', 'U2', 'Rock', 1987, 'Island Records', 'Very Good', 21.00, 'The fifth studio album by Irish rock band U2.'),
('Appetite for Destruction', 'Guns N'' Roses', 'Rock', 1987, 'Geffen Records', 'Good', 19.00, 'The debut studio album by American hard rock band Guns N'' Roses.'),
('London Calling', 'The Clash', 'Punk', 1979, 'CBS Records', 'Mint', 29.00, 'The third studio album by English punk rock band The Clash.'),
('A Night at the Opera', 'Queen', 'Rock', 1975, 'EMI', 'Near Mint', 26.00, 'The fourth studio album by the British rock band Queen.'),
('Who''s Next', 'The Who', 'Rock', 1971, 'Track Records', 'Very Good', 23.00, 'The fifth studio album by English rock band The Who.'),
('Houses of the Holy', 'Led Zeppelin', 'Rock', 1973, 'Atlantic Records', 'Good', 17.00, 'The fifth studio album by English rock band Led Zeppelin.'),
('The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'David Bowie', 'Rock', 1972, 'RCA Records', 'Mint', 31.00, 'The fifth studio album by English musician David Bowie.'),
('Exile on Main St.', 'The Rolling Stones', 'Rock', 1972, 'Rolling Stones Records', 'Near Mint', 28.00, 'The tenth studio album by English rock band The Rolling Stones.'),
('Sticky Fingers', 'The Rolling Stones', 'Rock', 1971, 'Rolling Stones Records', 'Very Good', 22.00, 'The ninth British and eleventh American studio album by The Rolling Stones.'),
('Revolver', 'The Beatles', 'Rock', 1966, 'Parlophone', 'Good', 20.00, 'The seventh studio album by the English rock band The Beatles.'),
('Pet Sounds', 'The Beach Boys', 'Rock', 1966, 'Capitol Records', 'Mint', 34.00, 'The eleventh studio album by American rock band The Beach Boys.'),
('Blonde on Blonde', 'Bob Dylan', 'Folk Rock', 1966, 'Columbia Records', 'Near Mint', 27.00, 'The seventh studio album by American singer-songwriter Bob Dylan.'),
('The Velvet Underground & Nico', 'The Velvet Underground', 'Rock', 1967, 'Verve Records', 'Very Good', 25.00, 'The debut album by American rock band The Velvet Underground and German singer Nico.'),
('OK Computer', 'Radiohead', 'Alternative', 1997, 'Parlophone', 'Good', 18.00, 'The third studio album by English rock band Radiohead.'),
('The Queen Is Dead', 'The Smiths', 'Alternative', 1986, 'Rough Trade', 'Mint', 29.00, 'The third studio album by English rock band The Smiths.'),
('Are You Experienced', 'The Jimi Hendrix Experience', 'Rock', 1967, 'Track Records', 'Near Mint', 26.00, 'The debut studio album by the Jimi Hendrix Experience.'),
('Kind of Blue', 'Miles Davis', 'Jazz', 1959, 'Columbia Records', 'Very Good', 24.00, 'A studio album by American jazz trumpeter Miles Davis.'),
('Blue', 'Joni Mitchell', 'Folk', 1971, 'Reprise Records', 'Good', 19.00, 'The fourth studio album by Canadian singer-songwriter Joni Mitchell.'),
('The Doors', 'The Doors', 'Rock', 1967, 'Elektra Records', 'Mint', 32.00, 'The debut studio album by American rock band The Doors.'),
('Highway 61 Revisited', 'Bob Dylan', 'Folk Rock', 1965, 'Columbia Records', 'Near Mint', 28.00, 'The sixth studio album by American singer-songwriter Bob Dylan.'),
('Electric Ladyland', 'The Jimi Hendrix Experience', 'Rock', 1968, 'Track Records', 'Very Good', 23.00, 'The third and final studio album by the Jimi Hendrix Experience.'),
('Blood on the Tracks', 'Bob Dylan', 'Folk Rock', 1975, 'Columbia Records', 'Good', 20.00, 'The fifteenth studio album by American singer-songwriter Bob Dylan.'),
('The Beatles (The White Album)', 'The Beatles', 'Rock', 1968, 'Apple Records', 'Mint', 35.00, 'The ninth studio album by the English rock band The Beatles.'),
('The Rolling Stones', 'The Rolling Stones', 'Rock', 1964, 'Decca', 'Near Mint', 27.00, 'The debut studio album by English rock band The Rolling Stones.'),
('Bridge Over Troubled Water', 'Simon & Garfunkel', 'Folk Rock', 1970, 'Columbia Records', 'Very Good', 22.00, 'The fifth and final studio album by American folk rock duo Simon & Garfunkel.'),
('Tapestry', 'Carole King', 'Pop', 1971, 'Ode Records', 'Good', 18.00, 'The second studio album by American singer-songwriter Carole King.'),
('The Freewheelin'' Bob Dylan', 'Bob Dylan', 'Folk', 1963, 'Columbia Records', 'Mint', 30.00, 'The second studio album by American singer-songwriter Bob Dylan.'),
('A Love Supreme', 'John Coltrane', 'Jazz', 1965, 'Impulse! Records', 'Near Mint', 29.00, 'A studio album by American jazz saxophonist John Coltrane.'),
('Never Mind the Bollocks, Here''s the Sex Pistols', 'Sex Pistols', 'Punk', 1977, 'Virgin Records', 'Very Good', 24.00, 'The only studio album by English punk rock band the Sex Pistols.'),
('The Clash', 'The Clash', 'Punk', 1977, 'CBS Records', 'Good', 19.00, 'The debut studio album by English punk rock band The Clash.'),
('Rumor and Sigh', 'Richard Thompson', 'Folk Rock', 1991, 'Capitol Records', 'Mint', 28.00, 'The sixth solo album by English singer-songwriter Richard Thompson.'),
('Harvest', 'Neil Young', 'Folk Rock', 1972, 'Reprise Records', 'Near Mint', 26.00, 'The fourth studio album by Canadian musician Neil Young.'),
('Hotel California', 'Eagles', 'Rock', 1976, 'Asylum Records', 'Very Good', 23.00, 'The fifth studio album by American rock band Eagles.'),
('The Marshall Mathers LP', 'Eminem', 'Hip Hop', 2000, 'Interscope Records', 'Good', 21.00, 'The third studio album by American rapper Eminem.'),
('Mothership Connection', 'Parliament', 'Funk', 1975, 'Casablanca Records', 'Mint', 30.00, 'The fourth album by American funk band Parliament.'),
('Innervisions', 'Stevie Wonder', 'Soul', 1973, 'Tamla', 'Near Mint', 27.00, 'The sixteenth studio album by American musician Stevie Wonder.'),
('Low', 'David Bowie', 'Rock', 1977, 'RCA Records', 'Very Good', 24.00, 'The eleventh studio album by English musician David Bowie.'),
('The Miseducation of Lauryn Hill', 'Lauryn Hill', 'Hip Hop', 1998, 'Ruffhouse Records', 'Good', 22.00, 'The debut solo album by American singer and rapper Lauryn Hill.'),
('Songs in the Key of Life', 'Stevie Wonder', 'Soul', 1976, 'Tamla', 'Mint', 34.00, 'The eighteenth studio album by American musician Stevie Wonder.'),
('The Chronic', 'Dr. Dre', 'Hip Hop', 1992, 'Death Row Records', 'Near Mint', 29.00, 'The debut studio album by American hip hop producer and rapper Dr. Dre.'),
('Graceland', 'Paul Simon', 'Pop', 1986, 'Warner Bros.', 'Very Good', 25.00, 'The seventh solo studio album by American singer-songwriter Paul Simon.'),
('Doolittle', 'Pixies', 'Alternative', 1989, '4AD', 'Good', 20.00, 'The second studio album by American alternative rock band Pixies.'),
('The Low End Theory', 'A Tribe Called Quest', 'Hip Hop', 1991, 'Jive Records', 'Mint', 32.00, 'The second studio album by American hip hop group A Tribe Called Quest.'),
('Blood Sugar Sex Magik', 'Red Hot Chili Peppers', 'Rock', 1991, 'Warner Bros.', 'Near Mint', 28.00, 'The fifth studio album by American rock band Red Hot Chili Peppers.'),
('The Smiths', 'The Smiths', 'Alternative', 1984, 'Rough Trade', 'Very Good', 25.00, 'The debut studio album by English rock band The Smiths.'),
('The Bends', 'Radiohead', 'Alternative', 1995, 'Parlophone', 'Good', 22.00, 'Second studio album by the English rock band Radiohead.'),
('Ten', 'Pearl Jam', 'Rock', 1991, 'Epic Records', 'Mint', 30.00, 'Debut studio album by American rock band Pearl Jam.'),
('Automatic for the People', 'R.E.M.', 'Alternative', 1992, 'Warner Bros.', 'Near Mint', 27.00, 'Eighth studio album by American alternative rock band R.E.M.'),
('Loveless', 'My Bloody Valentine', 'Alternative', 1991, 'Creation Records', 'Very Good', 26.00, 'Second studio album by the Irish-English rock band My Bloody Valentine.'),
('The Stone Roses', 'The Stone Roses', 'Alternative', 1989, 'Silvertone', 'Good', 23.00, 'Debut studio album by English rock band The Stone Roses.'),
('Grace', 'Jeff Buckley', 'Rock', 1994, 'Columbia Records', 'Mint', 31.00, 'Debut studio album by American singer-songwriter Jeff Buckley.'),
('Is This It', 'The Strokes', 'Rock', 2001, 'RCA Records', 'Near Mint', 28.00, 'Debut studio album by American rock band The Strokes.'),
('The College Dropout', 'Kanye West', 'Hip Hop', 2004, 'Roc-A-Fella Records', 'Very Good', 24.00, 'Debut studio album by American rapper and producer Kanye West.'),
('Elephant', 'The White Stripes', 'Rock', 2003, 'V2 Records', 'Good', 22.00, 'Fourth studio album by American rock duo The White Stripes.'),
('Turn On the Bright Lights', 'Interpol', 'Rock', 2002, 'Matador Records', 'Mint', 29.00, 'Debut studio album by American rock band Interpol.'),
('Yankee Hotel Foxtrot', 'Wilco', 'Alternative', 2002, 'Nonesuch Records', 'Near Mint', 27.00, 'Fourth studio album by American alternative rock band Wilco.'),
('The Black Album', 'Jay-Z', 'Hip Hop', 2003, 'Roc-A-Fella Records', 'Very Good', 26.00, 'Eighth studio album by American rapper Jay-Z.'),
('Funeral', 'Arcade Fire', 'Indie Rock', 2004, 'Merge Records', 'Good', 23.00, 'Debut studio album by Canadian indie rock band Arcade Fire.'),
('Back to Black', 'Amy Winehouse', 'Soul', 2006, 'Island Records', 'Mint', 31.00, 'Second and final studio album by English singer and songwriter Amy Winehouse.'),
('American Idiot', 'Green Day', 'Punk Rock', 2004, 'Reprise Records', 'Near Mint', 28.00, 'Seventh studio album by American rock band Green Day.'),
('A Rush of Blood to the Head', 'Coldplay', 'Alternative', 2002, 'Parlophone', 'Very Good', 25.00, 'Second studio album by British rock band Coldplay.'),
('The Eminem Show', 'Eminem', 'Hip Hop', 2002, 'Aftermath', 'Good', 22.00, 'Fourth studio album by American rapper Eminem.'),
('Good Kid, M.A.A.D City', 'Kendrick Lamar', 'Hip Hop', 2012, 'Top Dawg Entertainment', 'Mint', 33.00, 'Second studio album by American rapper Kendrick Lamar.'),
('Channel Orange', 'Frank Ocean', 'R&B', 2012, 'Def Jam Recordings', 'Near Mint', 30.00, 'Debut studio album by American singer Frank Ocean.'),
('My Beautiful Dark Twisted Fantasy', 'Kanye West', 'Hip Hop', 2010, 'Roc-A-Fella Records', 'Very Good', 28.00, 'Fifth studio album by American rapper and producer Kanye West.'),
('To Pimp a Butterfly', 'Kendrick Lamar', 'Hip Hop', 2015, 'Top Dawg Entertainment', 'Good', 25.00, 'Third studio album by American rapper Kendrick Lamar.'),
('Lemonade', 'Beyoncé', 'R&B', 2016, 'Parkwood Entertainment', 'Mint', 35.00, 'Sixth studio album by American singer Beyoncé.'),
('DAMN.', 'Kendrick Lamar', 'Hip Hop', 2017, 'Top Dawg Entertainment', 'Near Mint', 32.00, 'Fourth studio album by American rapper Kendrick Lamar.'),
('Blonde', 'Frank Ocean', 'R&B', 2016, 'Boys Don''t Cry', 'Very Good', 29.00, 'Second studio album by American singer Frank Ocean.'),
('Melodrama', 'Lorde', 'Pop', 2017, 'Lava Records', 'Good', 27.00, 'Second studio album by New Zealand singer Lorde.'),
('Currents', 'Tame Impala', 'Psychedelic Rock', 2015, 'Modular Recordings', 'Mint', 34.00, 'Third studio album by Australian musical project Tame Impala.'),
('Ctrl', 'SZA', 'R&B', 2017, 'Top Dawg Entertainment', 'Near Mint', 31.00, 'Debut studio album by American singer SZA.'),
('Anti', 'Rihanna', 'R&B', 2016, 'Westbury Road', 'Very Good', 28.00, 'Eighth studio album by American singer Rihanna.'),
('Views', 'Drake', 'Hip Hop', 2016, 'OVO Sound', 'Good', 25.00, 'Second studio album by American rapper Drake.'),
('The Life of Pablo', 'Pablo Honey', 'Alternative', 2003, 'EMI', 'Mint', 32.00, 'Second studio album by English rock band Pablo Honey.'),
('The College Dropout', 'Kanye West', 'Hip Hop', 2004, 'Roc-A-Fella Records', 'Near Mint', 29.00, 'Second studio album by American rapper and producer Kanye West.'),
('Future Nostalgia', 'Dua Lipa', 'Pop', 2020, 'Warner Records', 'Good', 27.00, 'Second studio album by English singer Dua Lipa.'),
('Folklore', 'Taylor Swift', 'Indie Folk', 2020, 'Republic Records', 'Mint', 34.00, 'Eighth studio album by American singer-songwriter Taylor Swift.'),
('After Hours', 'The Weeknd', 'R&B', 2020, 'XO', 'Near Mint', 31.00, 'Fourth studio album by Canadian singer The Weeknd.'),
('When We All Fall Asleep, Where Do We Go?', 'Billie Eilish', 'Pop', 2019, 'Interscope Records', 'Very Good', 28.00, 'Debut studio album by American singer Billie Eilish.'),
('FutureSex/LoveSounds', 'Justin Timberlake', 'Pop', 2006, 'Jive Records', 'Good', 26.00, 'Second studio album by American singer Justin Timberlake.'),
('good kid, m.A.A.d city', 'Kendrick Lamar', 'Hip Hop', 2012, 'Top Dawg Entertainment', 'Mint', 33.00, 'Second studio album by American rapper Kendrick Lamar.'),
('Take Care', 'Drake', 'Hip Hop', 2011, 'Young Money', 'Near Mint', 30.00, 'Second studio album by Canadian rapper Drake.'),
('Born to Die', 'Lana Del Rey', 'Pop', 2012, 'Interscope Records', 'Very Good', 28.00, 'Second studio album by American singer Lana Del Rey.'),
('Blurryface', 'Twenty One Pilots', 'Alternative', 2015, 'Fueled by Ramen', 'Good', 26.00, 'Fourth studio album by American musical duo Twenty One Pilots.'),
('Random Access Memories', 'Daft Punk', 'Electronic', 2013, 'Columbia Records', 'Mint', 35.00, 'Fourth studio album by French electronic duo Daft Punk.'),
('To Pimp a Butterfly', 'Kendrick Lamar', 'Hip Hop', 2015, 'Top Dawg Entertainment', 'Near Mint', 32.00, 'Third studio album by American rapper Kendrick Lamar.'),
('Ctrl', 'SZA', 'R&B', 2017, 'Top Dawg Entertainment', 'Very Good', 29.00, 'Debut studio album by American singer SZA.'),
('Astroworld', 'Travis Scott', 'Hip Hop', 2018, 'Cactus Jack', 'Good', 26.00, 'Third studio album by American rapper Travis Scott.');