(1, 'Back in Black', 'AC/DC', 'Rock', 1980, 'Atlantic', 'AC/DC: 1980 album, known for its electrifying rock sound and one of the best-selling albums of all time.'),
(2, 'The Dark Side of the Moon', 'Pink Floyd', 'Progressive Rock', 1973, 'Harvest', 'A concept album exploring the human experience with revolutionary sound and thematic depth.'),
(3, 'Thriller', 'Michael Jackson', 'Pop', 1982, 'Epic', 'Michael Jackson: 1982 record, a global phenomenon known for its innovative music videos and chart-topping hits.'),
(4, 'The Beatles', 'The Beatles', 'Rock', 1968, 'Apple', 'The Beatles: double album, often called the "White Album," showcasing their eclectic range of styles.'),
(5, 'Rumours', 'Fleetwood Mac', 'Rock', 1977, 'Warner Bros.', 'Fleetwood Mac: 1977 album, renowned for its emotional depth and classic rock anthems.'),
(6, 'Nevermind', 'Nirvana', 'Grunge', 1991, 'DGC', 'Nirvana 1991 breakthrough album that defined the grunge movement with its raw sound and poignant lyrics.'),
(7, 'Born to Run', 'Bruce Springsteen', 'Rock', 1975, 'Columbia', 'Springsteen: 1975 album, a landmark rock record with its epic storytelling and anthemic sound.'),
(8, 'Hotel California', 'Eagles', 'Rock', 1976, 'Asylum', 'The Eagles: 1976 album, famous for its lush production and the iconic title track.'),
(9, 'The Joshua Tree', 'U2', 'Rock', 1987, 'Island', 'U2s: 1987 album, blending rock with spiritual and political themes to create a timeless classic.'),
(10, 'Abbey Road', 'The Beatles', 'Rock', 1969, 'Apple', 'The Beatles: 1969 album, known for its innovative recording techniques and the iconic medley on Side B.'),
(11, 'Led Zeppelin IV', 'Led Zeppelin', 'Rock', 1971, 'Atlantic', 'A classic rock staple featuring "Stairway to Heaven" and a range of hard rock and acoustic tracks.'),
(12, 'A Night at the Opera', 'Queen', 'Rock', 1975, 'EMI', 'Queen 1975 album, famous for its operatic rock and the legendary "Bohemian Rhapsody."'),
(13, 'Kind of Blue', 'Miles Davis', 'Jazz', 1959, 'Columbia', 'Miles Davis: 1959 album, a cornerstone of jazz featuring a groundbreaking modal approach.'),
(14, 'In the Court of the Crimson King', 'King Crimson', 'Progressive Rock', 1969, 'Island', 'A landmark album in progressive rock with its complex structures and dark, atmospheric sound.'),
(15, 'Pet Sounds', 'The Beach Boys', 'Pop', 1966, 'Capitol', 'The Beach Boys: 1966 album, renowned for its sophisticated production and harmonically rich sound.'),
(16, 'To Pimp a Butterfly', 'Kendrick Lamar', 'Hip Hop', 2015, 'Top Dawg', 'Kendrick Lamar: 2015 album, a powerful exploration of race and identity with a diverse musical landscape.'),
(17, 'Blonde on Blonde', 'Bob Dylan', 'Folk Rock', 1966, 'Columbia', 'Bob Dylan: 1966 album, known for its complex lyrics and fusion of rock and folk influences.'),
(18, 'Born in the U.S.A.', 'Bruce Springsteen', 'Rock', 1984, 'Columbia', 'Springsteen: 1984 album, featuring anthems that explore American life and its struggles.'),
(19, 'The Suburbs', 'Arcade Fire', 'Indie Rock', 2010, 'Merge', 'Arcade Fire: 2010 album, acclaimed for its reflection on suburban life and its expansive, anthemic sound.'),
(20, 'Dark Side of the Moon', 'Pink Floyd', 'Progressive Rock', 1973, 'Harvest', 'Pink Floyd: iconic 1973 concept album, celebrated for its sonic innovation and thematic coherence.'),
(21, 'Goodbye Yellow Brick Road', 'Elton John', 'Pop', 1973, 'MCA', 'Elton John: 1973 double album, featuring a mix of pop hits and intricate compositions.'),
(22, 'The Wall', 'Pink Floyd', 'Progressive Rock', 1979, 'Columbia', 'Pink Floyd: 1979 rock opera, a profound exploration of isolation and mental anguish.'),
(23, 'The Bends', 'Radiohead', 'Alternative Rock', 1995, 'Parlophone', 'Radiohead: 1995 album, known for its emotive lyrics and innovative guitar work.'),
(24, 'Lust for Life', 'Iggy Pop', 'Rock', 1977, 'Arista', 'Iggy Pop: 1977 album, featuring a raw rock sound and energetic performances.'),
(25, 'Odessey and Oracle', 'The Zombies', 'Pop', 1968, 'Date', 'A psychedelic pop masterpiece with lush arrangements and enduring melodies.'),
(26, 'Genius of Modern Music', 'Thelonious Monk', 'Jazz', 1956, 'Blue Note', 'Monk: groundbreaking 1956 album, showcasing his unique compositions and improvisational style.'),
(27, 'A Love Supreme', 'John Coltrane', 'Jazz', 1965, 'Impulse!', 'John Coltrane: spiritual jazz suite, revered for its profound impact and innovative approach.'),
(28, 'Are You Experienced?', 'The Jimi Hendrix Experience', 'Rock', 1967, 'Reprise', 'Jimi Hendrix: groundbreaking debut, known for its innovative guitar work and psychedelic sound.'),
(29, 'Songs in the Key of Life', 'Stevie Wonder', 'Soul', 1976, 'Tamla', 'Stevie Wonder: 1976 double album, celebrated for its rich arrangements and lyrical depth.'),
(30, 'Electric Ladyland', 'The Jimi Hendrix Experience', 'Rock', 1968, 'Reprise', 'Jimi Hendrix: 1968 album, known for its experimental approach and psychedelic sound.'),
(31, 'Exile on Main St.', 'The Rolling Stones', 'Rock', 1972, 'Rolling Stones', 'The Rolling Stones: gritty 1972 album, known for its diverse styles and raw energy.'),
(32, 'Back to Black', 'Amy Winehouse', 'Soul', 2006, 'Island', 'Amy Winehouse: 2006 album, celebrated for its deep, soulful sound and confessional lyrics.'),
(33, 'The Queen Is Dead', 'The Smiths', 'Alternative Rock', 1986, 'Rough Trade', 'The Smiths: 1986 album, known for its introspective lyrics and influential sound.'),
(34, 'A Night at the Opera', 'Queen', 'Rock', 1975, 'EMI', 'Queen: 1975 album, known for its elaborate production and operatic rock songs.'),
(35, 'Tusk', 'Fleetwood Mac', 'Rock', 1979, 'Warner Bros.', 'Fleetwood Mac: ambitious 1979 double album, recognized for its experimental sound and diverse tracks.'),
(36, 'The Low End Theory', 'A Tribe Called Quest', 'Hip Hop', 1991, 'Jive', 'A Tribe Called Quest: 1991 album, influential in shaping the sound of hip-hop with its jazzy beats and insightful lyrics.'),
(37, 'Blue Lines', 'Massive Attack', 'Trip Hop', 1991, 'Virgin', 'Massive Attack: 1991 debut, pioneering the trip-hop genre with its atmospheric and moody sound.'),
(38, 'Blonde on Blonde', 'Bob Dylan', 'Folk Rock', 1966, 'Columbia', 'Dylan: 1966 double album, a landmark in rock with its poetic lyrics and diverse sound.'),
(39, 'Houses of the Holy', 'Led Zeppelin', 'Rock', 1973, 'Atlantic', 'Led Zeppelin: 1973 album, showcasing a mix of hard rock and experimental sounds.'),
(40, 'In Utero', 'Nirvana', 'Grunge', 1993, 'DGC', 'Nirvana: 1993 follow-up to "Nevermind," known for its raw sound and darker themes.'),
(41, 'The Piper at the Gates of Dawn', 'Pink Floyd', 'Psychedelic Rock', 1967, 'Columbia', 'Pink Floyd: 1967 debut, a seminal work in psychedelic rock with its experimental sounds.'),
(42, 'The Essential Bob Dylan', 'Bob Dylan', 'Folk Rock', 2000, 'Columbia', 'A compilation of Bob Dylan: most impactful tracks, highlighting his influence on

 rock and folk music.'),
(43, 'Greatest Hits', 'ABBA', 'Pop', 1975, 'Epic', 'ABBA: compilation album, featuring their most memorable hits and pop classics.'),
(44, 'Hymns to the Silence', 'Van Morrison', 'Rock', 1991, 'Mercury', 'Van Morrison: 1991 release, known for its introspective lyrics and soulful melodies.'),
(45, 'Paranoid', 'Black Sabbath', 'Heavy Metal', 1970, 'Vertigo', 'Black Sabbath: 1970 album, a milestone in heavy metal with its dark, powerful riffs.'),
(46, 'Born to Run', 'Bruce Springsteen', 'Rock', 1975, 'Columbia', 'A seminal rock album by Bruce Springsteen, celebrated for its epic sound and lyrical storytelling.'),
(47, 'The Very Best of The Kinks', 'The Kinks', 'Rock', 1998, 'Castle', 'A compilation of The Kinks: greatest hits, highlighting their unique sound and influence.'),
(48, 'American Recordings', 'Johnny Cash', 'Country', 1994, 'American', 'Johnny Cash: 1994 album, noted for its stripped-down production and emotional resonance.'),
(49, 'Goodbye Yellow Brick Road', 'Elton John', 'Pop', 1973, 'MCA', 'Elton John: 1973 album, showcasing his range of pop and rock styles with memorable tracks.'),
(50, 'Who’s Next', 'The Who', 'Rock', 1971, 'Decca', 'The Who: 1971 album, known for its innovative use of synthesizers and powerful rock sound.'),
(51, 'Tales of Mystery and Imagination', 'Alan Parsons Project', 'Progressive Rock', 1976, 'Arista', 'Alan Parsons Project: 1976 debut, a concept album inspired by Edgar Allan Poes works.'),
(52, 'Live at Leeds', 'The Who', 'Rock', 1970, 'Track', 'The Who: 1970 live album, celebrated for its raw energy and electrifying performances.'),
(53, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'David Bowie', 'Rock', 1972, 'RCA', 'David Bowie: 1972 concept album, featuring his iconic Ziggy Stardust persona and innovative rock sound.'),
(54, 'Songs of Leonard Cohen', 'Leonard Cohen', 'Folk', 1967, 'Columbia', 'Leonard Cohen: 1967 debut, known for its profound lyrics and Cohens deep, resonant voice.'),
(55, 'The Band', 'The Band', 'Rock', 1969, 'Capitol', 'The Band: self-titled 1969 album, blending rock with Americana influences.'),
(56, 'Are You Experienced?', 'The Jimi Hendrix Experience', 'Rock', 1967, 'Reprise', 'Jimi Hendrix: 1967 debut, showcasing his groundbreaking guitar techniques and psychedelic sound.'),
(57, 'Greatest Hits', 'Elton John', 'Pop', 1974, 'MCA', 'A collection of Elton John: most popular songs from the early 1970s, displaying his pop brilliance.'),
(58, 'White Album', 'The Beatles', 'Rock', 1968, 'Apple', 'The Beatles: 1968 double album, known for its eclectic mix of styles and experimental approach.'),
(59, 'The Essential Johnny Cash', 'Johnny Cash', 'Country', 2002, 'Columbia', 'A compilation of Johnny Cash: most influential tracks, highlighting his powerful storytelling.'),
(60, 'Never Mind the Bollocks, Here’s the Sex Pistols', 'Sex Pistols', 'Punk Rock', 1977, 'Virgin', 'The Sex Pistols: 1977 debut, a cornerstone of punk rock with its raw sound and rebellious attitude.'),
(61, 'Electric Warrior', 'T. Rex', 'Glam Rock', 1971, 'T. Rex', 'T. Rex: 1971 album, a defining release in glam rock with catchy melodies and flamboyant style.'),
(62, 'Songs in the Key of Life', 'Stevie Wonder', 'Soul', 1976, 'Tamla', 'Stevie Wonder: 1976 double album, acclaimed for its rich musicality and lyrical depth.'),
(63, 'Rumours', 'Fleetwood Mac', 'Rock', 1977, 'Warner Bros.', 'Fleetwood Mac: 1977 album, a rock classic known for its emotional and musical complexity.'),
(64, 'The Very Best of The Kinks', 'The Kinks', 'Rock', 1998, 'Castle', 'A collection of The Kinks: greatest hits, reflecting their distinctive sound and influence.'),
(65, 'The Queen Is Dead', 'The Smiths', 'Alternative Rock', 1986, 'Rough Trade', 'The Smiths: 1986 album, known for its melancholic lyrics and influential alternative rock sound.'),
(66, 'Songs of Innocence', 'U2', 'Rock', 2014, 'Island', 'U2: 2014 album, exploring themes of innocence with a polished rock sound.'),
(67, 'Lonesome Dreams', 'Foy Vance', 'Country', 2014, 'RCA', 'Foy Vance: 2014 release, blending folk and country with heartfelt lyrics and melodies.'),
(68, 'Blonde on Blonde', 'Bob Dylan', 'Folk Rock', 1966, 'Columbia', 'Bob Dylan: 1966 album, an influential work in folk rock with its complex lyrics and innovative sound.'),
(69, 'The Essential Johnny Cash', 'Johnny Cash', 'Country', 2002, 'Columbia', 'A collection of Johnny Cash: most iconic tracks, showcasing his deep, resonant voice and storytelling.'),
(70, 'Back in Black', 'AC/DC', 'Rock', 1980, 'Atlantic', 'AC/DC: 1980 release, celebrated for its powerful riffs and enduring rock anthems.'),
(71, 'Legend', 'Bob Marley and the Wailers', 'Reggae', 1984, 'Island', 'A compilation of Bob Marley greatest hits, highlighting his revolutionary reggae sound.'),
(72, 'Goodbye Yellow Brick Road', 'Elton John', 'Pop', 1973, 'MCA', 'Elton John: 1973 classic, featuring a mix of pop and rock with elaborate production.'),
(73, 'Songs of Innocence', 'U2', 'Rock', 2014, 'Island', 'U2: 2014 album, a polished rock exploration of youth and innocence.'),
(74, 'Tales of Mystery and Imagination', 'Alan Parsons Project', 'Progressive Rock', 1976, 'Arista', 'Alan Parsons Project: 1976 debut, a concept album based on Edgar Allan Poe.'),
(75, 'The Best of David Bowie', 'David Bowie', 'Rock', 1980, 'RCA', 'A compilation of David Bowie most influential tracks, showcasing his innovative career.'),
(76, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'David Bowie', 'Rock', 1972, 'RCA', 'David Bowie: 1972 concept album, featuring his iconic Ziggy Stardust persona.'),
(77, 'American Music Club', 'California', 'Alternative Rock', 1988, 'Reprise', 'American Music Club: 1988 album, praised for its introspective lyrics and alternative rock sound.'),
(78, 'Songs in the Key of Life', 'Stevie Wonder', 'Soul', 1976, 'Tamla', 'Stevie Wonder: 1976 double album, known for its rich musical arrangements and lyrical depth.'),
(79, 'The Clash', 'The Clash', 'Punk Rock', 1977, 'CBS', 'The Clash: 1977 debut, a seminal punk rock album with energetic tracks and political commentary.'),
(80, 'Electric Warrior', 'T. Rex', 'Glam Rock', 1971, 'T. Rex', 'T. Rex: 1971 album, known for its glam rock style and catchy, flamboyant songs.'),
(81, 'A Hard Day’s Night', 'The Beatles', 'Rock', 1964, 'Parlophone', 'The Beatles: 1964 album, featuring their early hits and a vibrant rock sound.'),
(82, 'Never Mind the Bollocks, Here’s the Sex Pistols', 'Sex Pistols', 'Punk Rock', 1977, 'Virgin', 'Sex Pistols: 1977 debut, a defining punk rock album with its raw energy and rebellious spirit.'),
(83, 'The Best of The Doors', 'The Doors', 'Rock', 1985, 'Elektra', 'A compilation of The Doors greatest tracks, showcasing their distinctive rock sound.'),
(84, 'Back in Black', 'AC/DC', 'Rock', 1980, 'Atlantic', 'AC/DC: 1980 album, known for its high-energy rock sound and iconic riffs.'),
(85, 'The Essential Johnny Cash', 'Johnny Cash', 'Country', 2002, 'Columbia', 'A compilation album featuring Johnny Cash most influential

 songs.'),
(86, 'Live at the Apollo', 'James Brown', 'Soul', 1963, 'King', 'James Brown: 1963 live album, capturing his electrifying stage presence and soul music impact.'),
(87, 'Blonde on Blonde', 'Bob Dylan', 'Folk Rock', 1966, 'Columbia', 'Dylan: 1966 double album, a pivotal release in folk rock with its poetic lyrics.'),
(88, 'Goodbye Yellow Brick Road', 'Elton John', 'Pop', 1973, 'MCA', 'Elton John: 1973 album, known for its elaborate production and wide-ranging pop hits.'),
(89, 'Legend', 'Bob Marley and the Wailers', 'Reggae', 1984, 'Island', 'A compilation of Bob Marley greatest reggae tracks, featuring his revolutionary sound.'),
(90, 'Are You Experienced?', 'The Jimi Hendrix Experience', 'Rock', 1967, 'Reprise', 'Hendrix: 1967 debut, showcasing his groundbreaking guitar techniques and psychedelic style.'),
(91, 'Pet Sounds', 'The Beach Boys', 'Pop', 1966, 'Capitol', 'The Beach Boys: 1966 album, a revolutionary work in pop music with its intricate production.'),
(92, 'In the Court of the Crimson King', 'King Crimson', 'Progressive Rock', 1969, 'Island', 'King Crimson: 1969 debut, a landmark in progressive rock with its dark, complex sound.'),
(93, 'Songs of Innocence', 'U2', 'Rock', 2014, 'Island', 'U2: 2014 release, exploring themes of innocence with a polished, modern rock approach.'),
(94, 'Songs of Leonard Cohen', 'Leonard Cohen', 'Folk', 1967, 'Columbia', 'Leonard Cohen: debut album, known for its deep lyrical content and unique vocal style.'),
(95, 'Blonde on Blonde', 'Bob Dylan', 'Folk Rock', 1966, 'Columbia', 'A seminal folk rock album by Dylan, known for its complex lyrics and innovative sound.'),
(96, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'David Bowie', 'Rock', 1972, 'RCA', 'Bowie: 1972 concept album, featuring his iconic Ziggy Stardust persona.'),
(97, 'Songs in the Key of Life', 'Stevie Wonder', 'Soul', 1976, 'Tamla', 'Wonder: 1976 double album, celebrated for its rich musicality and depth.'),
(98, 'Live at Leeds', 'The Who', 'Rock', 1970, 'Track', 'The Who: 1970 live recording, capturing their powerful stage presence and rock energy.'),
(99, 'A Hard Day’s Night', 'The Beatles', 'Rock', 1964, 'Parlophone', 'The Beatles: 1964 album, featuring some of their earliest and most beloved rock hits.'),
(100, 'Exile on Main St.', 'The Rolling Stones', 'Rock', 1972, 'Rolling Stones', 'The Rolling Stones: influential 1972 album, noted for its raw, diverse rock sound.'),
(101, 'The Clash', 'The Clash', 'Punk Rock', 1977, 'CBS', 'The Clash: debut album, a key release in punk rock with its energetic and political edge.'),
(102, 'Blonde on Blonde', 'Bob Dylan', 'Folk Rock', 1966, 'Columbia', 'Dylan: 1966 album, a major work in folk rock with its poetic depth and musical innovation.');