INSERT INTO public."records"(
	record_id, title, artist, genre, "ReleaseYear", label, description)
	VALUES
(1, 'Back in Black', 'AC/DC', 'Rock', 1980, 'Atlantic', 'AC/DC: 1980 album, known for its electrifying rock sound and one of the best-selling albums of all time.'),
(2, 'Thriller', 'Michael Jackson', 'Pop', 1982, 'Epic', 'Michael Jackson''s Thriller is the best-selling album of all time with iconic tracks like ''Beat It'' and ''Billie Jean''.'),
(3, 'The Dark Side of the Moon', 'Pink Floyd', 'Rock', 1973, 'Harvest', 'A seminal album in rock history, Pink Floyd''s The Dark Side of the Moon is renowned for its innovative production and cohesive theme.'),
(4, 'Rumours', 'Fleetwood Mac', 'Rock', 1977, 'Warner Bros.', 'Fleetwood Mac''s Rumours is a critically acclaimed album known for its harmonious blend of rock and pop and personal, introspective lyrics.'),
(5, 'Abbey Road', 'The Beatles', 'Rock', 1969, 'Apple', 'Abbey Road by The Beatles is famous for its seamless medley on the B-side and iconic cover photo.'),
(6, 'Led Zeppelin IV', 'Led Zeppelin', 'Rock', 1971, 'Atlantic', 'Featuring ''Stairway to Heaven'', Led Zeppelin IV is considered one of the greatest rock albums of all time.'),
(7, 'Hotel California', 'Eagles', 'Rock', 1976, 'Asylum', 'Eagles'' Hotel California is known for its title track and deep, complex lyrics and arrangements.'),
(8, 'Born to Run', 'Bruce Springsteen', 'Rock', 1975, 'Columbia', 'Bruce Springsteen''s Born to Run is a rock classic known for its powerful anthems and emotional depth.'),
(9, 'The Wall', 'Pink Floyd', 'Rock', 1979, 'Harvest', 'A rock opera, Pink Floyd''s The Wall is a narrative-driven album that explores themes of isolation and self-imposed barriers.'),
(10, 'Goodbye Yellow Brick Road', 'Elton John', 'Pop', 1973, 'MCA', 'Elton John''s Goodbye Yellow Brick Road is celebrated for its wide range of musical styles and storytelling.'),
(11, 'Purple Rain', 'Prince', 'Pop', 1984, 'Warner Bros.', 'Prince''s Purple Rain is a landmark album known for its fusion of rock, pop, and R&B, and the hit single ''Purple Rain''.'),
(12, 'Nevermind', 'Nirvana', 'Grunge', 1991, 'DGC', 'Nirvana''s Nevermind brought grunge music to the mainstream with hits like ''Smells Like Teen Spirit''.'),
(13, 'The Joshua Tree', 'U2', 'Rock', 1987, 'Island', 'U2''s The Joshua Tree is known for its atmospheric sound and politically charged lyrics.'),
(14, 'London Calling', 'The Clash', 'Punk', 1979, 'CBS', 'The Clash''s London Calling is a genre-blending masterpiece that spans punk, reggae, ska, and rockabilly.'),
(15, 'A Night at the Opera', 'Queen', 'Rock', 1975, 'EMI', 'Queen''s A Night at the Opera features the legendary ''Bohemian Rhapsody'' and showcases the band''s eclectic style.'),
(16, 'Appetite for Destruction', 'Guns N'' Roses', 'Rock', 1987, 'Geffen', 'Guns N'' Roses'' debut album, Appetite for Destruction, is renowned for its raw energy and hit tracks like ''Sweet Child o'' Mine''.'),
(17, 'Sgt. Pepper''s Lonely Hearts Club Band', 'The Beatles', 'Rock', 1967, 'Parlophone', 'The Beatles'' Sgt. Pepper''s Lonely Hearts Club Band is a groundbreaking concept album that redefined the boundaries of rock music.'),
(18, 'Tapestry', 'Carole King', 'Pop', 1971, 'Ode', 'Carole King''s Tapestry is a landmark album in singer-songwriter history, featuring timeless classics like ''It''s Too Late'' and ''You''ve Got a Friend''.'),
(19, 'Who''s Next', 'The Who', 'Rock', 1971, 'Decca', 'The Who''s Who''s Next is hailed for its powerful rock anthems and innovative use of synthesizers.'),
(20, 'Graceland', 'Paul Simon', 'Pop', 1986, 'Warner Bros.', 'Paul Simon''s Graceland is an influential album known for its fusion of pop and African musical styles.'),
(21, 'Hotel Newfoundland', 'Eagles', 'Rock', 1976, 'Asylum', 'Eagles'' Hotel Newfoundland is a classic rock album featuring the hit title track and exploring themes of excess and disillusionment.'),
(22, 'Gossip', 'Around da Bay Girls', 'Rock', 1977, 'Warner Bros.', 'Fleetwood Mac''s Gossip is a timeless album known for its harmonious blend of rock and pop, and introspective lyrics.'),
(23, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'David Bowie', 'Rock', 1972, 'RCA', 'David Bowie''s Ziggy Stardust is a concept album that tells the story of a fictional rock star and is praised for its innovative style.'),
(24, 'A Love Supreme', 'John Coltrane', 'Jazz', 1965, 'Impulse!', 'John Coltrane''s A Love Supreme is a deeply spiritual and influential jazz album that showcases his virtuosic saxophone playing.'),
(25, 'Pet Sounds', 'The Beach Boys', 'Pop', 1966, 'Capitol', 'The Beach Boys'' Pet Sounds is a groundbreaking album that pushed the boundaries of pop music with its lush arrangements and introspective lyrics.'),
(26, 'Blood on the Tracks', 'Bob Dylan', 'Folk', 1975, 'Columbia', 'Bob Dylan''s Blood on the Tracks is a deeply personal and critically acclaimed album that features some of his most enduring songs.'),
(27, 'Blue', 'Joni Mitchell', 'Folk', 1971, 'Reprise', 'Joni Mitchell''s Blue is a seminal album in the singer-songwriter genre, known for its emotional depth and poetic lyrics.'),
(28, 'Highway 61 Revisited', 'Bob Dylan', 'Rock', 1965, 'Columbia', 'Bob Dylan''s Highway 61 Revisited is a landmark album in rock music, featuring the iconic track ''Like a Rolling Stone''.'),
(29, 'Blonde on Blonde', 'Bob Dylan', 'Rock', 1966, 'Columbia', 'Bob Dylan''s Blonde on Blonde is a double album that is considered one of his greatest works, blending rock, folk, and blues.'),
(30, 'Exile on Main St.', 'The Rolling Stones', 'Rock', 1972, 'Rolling Stones', 'The Rolling Stones'' Exile on Main St. is a sprawling double album that captures the band''s raw energy and eclectic style.'),
(31, 'Tunes in the Key of Life', 'Stevie Sadness', 'R&B', 1976, 'Tamla', 'Stevie Wonder''s Songs in the Key of Life is a double album that showcases his musical genius and addresses social issues.'),
(32, 'The Velvet Underground & Nico', 'The Velvet Underground', 'Rock', 1967, 'Verve', 'The Velvet Underground''s debut album, featuring Nico, is a groundbreaking work that influenced countless artists with its experimental sound.'),
(33, 'Bitches Brew', 'Miles Davis', 'Jazz', 1970, 'Columbia', 'Miles Davis'' Bitches Brew is a revolutionary jazz album that blends jazz with rock and electronic music, creating a new genre.'),
(34, 'Kind of Blue', 'Miles Davis', 'Jazz', 1959, 'Columbia', 'Miles Davis'' Kind of Blue is one of the most influential jazz albums of all time, known for its improvisational style and modal jazz.'),
(35, 'Ponys', 'Patti John', 'Rock', 1975, 'Arista', 'Patti Smith''s Horses is a landmark punk rock album that combines poetry and rock music, challenging traditional gender roles.'),
(36, 'Marquee Moon', 'Television', 'Rock', 1977, 'Elektra', 'Television''s Marquee Moon is a seminal album in the punk rock genre, known for its intricate guitar work and complex song structures.'),
(37, 'Transformer', 'Lou Reed', 'Rock', 1972, 'RCA', 'Lou Reed''s Transformer is a glam rock classic that includes the hit singles ''Walk on the Wild Side'' and ''Perfect Day''.'),
(38, 'Roxy Music', 'Roxy Music', 'Rock', 1972, 'Island', 'Roxy Music''s debut album is a pioneering work of art rock, blending elements of glam rock, avant-garde, and pop.'),
(39, 'Harvest', 'Neil Young', 'Folk', 1972, 'Reprise', 'Neil Young''s Harvest is a critically acclaimed folk rock album featuring the hit single ''Heart of Gold''.'),
(40, 'Bridge Over Troubled Water', 'Simon & Garfunkel', 'Folk', 1970, 'Columbia', 'Simon & Garfunkel''s Bridge Over Troubled Water is a timeless album known for its beautiful harmonies and introspective lyrics.'),
(41, 'After the Gold Rush', 'Neil Young', 'Rock', 1970, 'Reprise', 'Neil Young''s After the Gold Rush is a landmark album in the singer-songwriter genre, known for its raw emotion and lyrical depth.'),
(42, 'Ziggy Stardust', 'David Bowie', 'Rock', 1972, 'RCA', 'David Bowie''s Ziggy Stardust is a groundbreaking concept album that tells the story of a fictional rock star.'),
(43, 'The Chronic', 'Dr. Dre', 'Hip Hop', 1992, 'Death Row', 'Dr. Dre''s The Chronic is a landmark album in West Coast hip hop, known for its innovative production and influential sound.'),
(44, 'Straight Outta Compton', 'N.W.A', 'Hip Hop', 1988, 'Ruthless', 'N.W.A''s Straight Outta Compton is a seminal album in gangsta rap, known for its raw, unfiltered portrayal of urban life.'),
(45, 'The Miseducation of Lauryn Hill', 'Lauryn Hill', 'R&B', 1998, 'Ruffhouse', 'Lauryn Hill''s The Miseducation of Lauryn Hill is a critically acclaimed album that blends R&B, hip hop, and soul.'),
(46, 'Illmatic', 'Nas', 'Hip Hop', 1994, 'Columbia', 'Nas'' Illmatic is a groundbreaking album in East Coast hip hop, known for its lyrical prowess and storytelling.'),
(47, 'Ready to Die', 'The Notorious B.I.G.', 'Hip Hop', 1994, 'Bad Boy', 'The Notorious B.I.G.''s Ready to Die is a landmark album in hip hop, known for its raw and introspective lyrics.'),
(48, 'To Pimp a Butterfly', 'Kendrick Lamar', 'Hip Hop', 2015, 'Top Dawg', 'Kendrick Lamar''s To Pimp a Butterfly is a critically acclaimed album that blends hip hop, jazz, and funk, and addresses social issues.'),
(49, 'The Marshall Mathers LP', 'Eminem', 'Hip Hop', 2000, 'Aftermath', 'Eminem''s The Marshall Mathers LP is a controversial and influential album known for its dark themes and lyrical complexity.'),
(50, 'Stankonia', 'OutKast', 'Hip Hop', 2000, 'LaFace', 'OutKast''s Stankonia is a groundbreaking album that blends hip hop, funk, and rock, and features the hit singles ''Ms. Jackson'' and ''B.O.B.''.'),
(51, 'The Blueprint', 'Jay-Z', 'Hip Hop', 2001, 'Roc-A-Fella', 'Jay-Z''s The Blueprint is a critically acclaimed album that features soulful production and introspective lyrics.'),
(52, 'Speakerboxxx/The Love Below', 'OutKast', 'Hip Hop', 2003, 'LaFace', 'OutKast''s double album Speakerboxxx/The Love Below showcases the duo''s eclectic style and features the hit singles ''Hey Ya!'' and ''The Way You Move''.'),
(53, 'The Low End Theory', 'A Tribe Called Quest', 'Hip Hop', 1991, 'Jive', 'A Tribe Called Quest''s The Low End Theory is a landmark album in jazz rap, known for its innovative production and smooth, lyrical flow.'),
(54, 'Madvillainy', 'Madvillain', 'Hip Hop', 2004, 'Stones Throw', 'Madvillain''s Madvillainy is a critically acclaimed underground hip hop album that features the unique production of Madlib and the distinctive flow of MF DOOM.'),
(55, 'Doggystyle', 'Snoop Dogg', 'Hip Hop', 1993, 'Death Row', 'Snoop Dogg''s Doggystyle is a seminal album in West Coast hip hop, known for its laid-back style and smooth production.'),
(56, 'Aquarius', 'Tinashe', 'R&B', 2014, 'RCA', 'Tinashe''s debut album Aquarius is a blend of R&B, hip hop, and pop, featuring the hit single ''2 On''.'),
(57, 'Ctrl', 'SZA', 'R&B', 2017, 'Top Dawg', 'SZA''s Ctrl is a critically acclaimed album that blends R&B, hip hop, and alternative, and explores themes of love and self-discovery.'),
(58, 'Anti', 'Rihanna', 'R&B', 2016, 'Roc Nation', 'Rihanna''s Anti is a genre-blending album that features hit singles ''Work'' and ''Needed Me''.'),
(59, 'Orange Juice', 'Beytwice', 'R&B', 2016, 'Parkwood', 'Beyoncé''s Lemonade is a critically acclaimed album that blends R&B, hip hop, and rock, and explores themes of love, betrayal, and empowerment.'),
(60, 'Channel Orange', 'Frank Ocean', 'R&B', 2012, 'Def Jam', 'Frank Ocean''s Channel Orange is a critically acclaimed album that blends R&B, soul, and funk, and features the hit single ''Thinkin Bout You''.'),
(61, 'House of Balloons', 'The Weeknd', 'R&B', 2011, 'XO', 'The Weeknd''s House of Balloons is a genre-defining album that blends R&B, hip hop, and electronic music, and explores themes of love, lust, and excess.'),
(62, 'The College Dropout', 'Kanye West', 'Hip Hop', 2004, 'Roc-A-Fella', 'Kanye West''s The College Dropout is a groundbreaking album that blends hip hop, soul, and gospel, and features the hit single ''Jesus Walks''.'),
(63, 'My Beautiful Dark Twisted Fantasy', 'Kanye West', 'Hip Hop', 2010, 'Def Jam', 'Kanye West''s My Beautiful Dark Twisted Fantasy is a critically acclaimed album that blends hip hop, R&B, and rock, and explores themes of fame, love, and self-destruction.'),
(64, 'Yeezus', 'Kanye West', 'Hip Hop', 2013, 'Def Jam', 'Kanye West''s Yeezus is a genre-defying album that blends hip hop, industrial, and electronic music, and features the hit single ''Black Skinhead''.'),
(65, 'The Life of Pablo', 'Kanye West', 'Hip Hop', 2016, 'Def Jam', 'Kanye West''s The Life of Pablo is a genre-blending album that features elements of hip hop, R&B, and gospel, and explores themes of love, faith, and fame.'),
(66, 'DAMN.', 'Kendrick Lamar', 'Hip Hop', 2017, 'Top Dawg', 'Kendrick Lamar''s DAMN. is a critically acclaimed album that blends hip hop, R&B, and funk, and features the hit single ''HUMBLE.''.'),
(67, 'Astroworld', 'Travis Scott', 'Hip Hop', 2018, 'Epic', 'Travis Scott''s Astroworld is a genre-blending album that features elements of hip hop, trap, and psychedelic music, and features the hit single ''SICKO MODE''.'),
(68, 'Take Care', 'Drake', 'Hip Hop', 2011, 'Young Money', 'Drake''s Take Care is a critically acclaimed album that blends hip hop, R&B, and pop, and features the hit single ''Marvins Room''.'),
(69, 'Views', 'Drake', 'Hip Hop', 2016, 'Young Money', 'Drake''s Views is a genre-blending album that features elements of hip hop, R&B, and dancehall, and features the hit single ''Hotline Bling''.'),
(70, 'If You''re Reading This It''s Too Late', 'Drake', 'Hip Hop', 2015, 'Young Money', 'Drake''s If You''re Reading This It''s Too Late is a critically acclaimed mixtape that features the hit single ''Energy''.'),
(71, 'Nothing Was the Same', 'Drake', 'Hip Hop', 2013, 'Young Money', 'Drake''s Nothing Was the Same is a genre-blending album that features elements of hip hop, R&B, and pop, and features the hit single ''Started From the Bottom''.'),
(72, 'Culture', 'Migos', 'Hip Hop', 2017, 'Quality Control', 'Migos'' Culture is a critically acclaimed album that features the hit single ''Bad and Boujee''.'),
(73, 'Culture II', 'Migos', 'Hip Hop', 2018, 'Quality Control', 'Migos'' Culture II is a genre-blending album that features elements of hip hop, trap, and pop, and features the hit single ''Stir Fry''.'),
(74, 'Good Kid, M.A.A.D City', 'Kendrick Lamar', 'Hip Hop', 2012, 'Top Dawg', 'Kendrick Lamar''s Good Kid, M.A.A.D City is a critically acclaimed album that tells the story of his upbringing in Compton, and features the hit single ''Swimming Pools (Drank)''.'),
(75, 'Acid Rap', 'Chance the Rapper', 'Hip Hop', 2013, 'Self-released', 'Chance the Rapper''s Acid Rap is a critically acclaimed mixtape that blends hip hop, R&B, and jazz, and features the hit single ''Cocoa Butter Kisses''.'),
(76, 'Coloring Book', 'Chance the Rapper', 'Hip Hop', 2016, 'Self-released', 'Chance the Rapper''s Coloring Book is a genre-blending album that features elements of hip hop, gospel, and R&B, and features the hit single ''No Problem''.'),
(77, 'The Carter III', 'Lil Wayne', 'Hip Hop', 2008, 'Young Money', 'Lil Wayne''s The Carter III is a critically acclaimed album that features the hit single ''Lollipop''.'),
(78, 'Tha Carter IV', 'Lil Wayne', 'Hip Hop', 2011, 'Young Money', 'Lil Wayne''s Tha Carter IV is a genre-blending album that features elements of hip hop, R&B, and pop, and features the hit single ''6 Foot 7 Foot''.'),
(79, 'Blonde', 'Frank Ocean', 'R&B', 2016, 'Boys Don''t Cry', 'Frank Ocean''s Blonde is a critically acclaimed album that blends R&B, pop, and electronic music, and explores themes of love, loss, and identity.'),
(80, 'Horses', 'Patti Smith', 'Punk Rock', 1975, 'Arista', 'Patti Smith''s Horses is a seminal album in punk rock, known for its raw energy and poetic lyrics.'),
(81, 'Exodus', 'Bob Marley and the Wailers', 'Reggae', 1977, 'Island', 'Bob Marley''s Exodus is a landmark reggae album that features the hit singles ''Jamming'' and ''One Love''.'),
(82, 'Catch a Fire', 'Bob Marley and the Wailers', 'Reggae', 1973, 'Island', 'Bob Marley''s Catch a Fire is a critically acclaimed album that blends reggae, rock, and soul, and features the hit single ''Stir It Up''.'),
(83, 'Rastaman Vibration', 'Bob Marley and the Wailers', 'Reggae', 1976, 'Island', 'Bob Marley''s Rastaman Vibration is a landmark reggae album that features the hit single ''Roots, Rock, Reggae''.'),
(84, 'Songs in the Key of Life', 'Stevie Wonder', 'R&B', 1976, 'Tamla', 'Stevie Wonder''s Songs in the Key of Life is a critically acclaimed album that blends R&B, soul, and funk, and features the hit single ''Sir Duke''.'),
(85, 'Innervisions', 'Stevie Wonder', 'R&B', 1973, 'Tamla', 'Stevie Wonder''s Innervisions is a critically acclaimed album that blends R&B, soul, and funk, and features the hit single ''Higher Ground''.'),
(86, 'Talking Book', 'Stevie Wonder', 'R&B', 1972, 'Tamla', 'Stevie Wonder''s Talking Book is a critically acclaimed album that blends R&B, soul, and funk, and features the hit single ''Superstition''.'),
(87, 'Hotter than July', 'Stevie Wonder', 'R&B', 1980, 'Tamla', 'Stevie Wonder''s Hotter than July is a critically acclaimed album that blends R&B, soul, and funk, and features the hit single ''Master Blaster (Jammin'')''.'),
(88, 'Songs in A Minor', 'Alicia Keys', 'R&B', 2001, 'J Records', 'Alicia Keys'' Songs in A Minor is a critically acclaimed album that blends R&B, soul, and pop, and features the hit single ''Fallin''.'),
(89, 'The Diary of Alicia Keys', 'Alicia Keys', 'R&B', 2003, 'J Records', 'Alicia Keys'' The Diary of Alicia Keys is a critically acclaimed album that blends R&B, soul, and pop, and features the hit single ''You Don''t Know My Name''.'),
(90, 'As I Am', 'Alicia Keys', 'R&B', 2007, 'J Records', 'Alicia Keys'' As I Am is a critically acclaimed album that blends R&B, soul, and pop, and features the hit single ''No One''.'),
(91, 'The Element of Freedom', 'Alicia Keys', 'R&B', 2009, 'J Records', 'Alicia Keys'' The Element of Freedom is a critically acclaimed album that blends R&B, soul, and pop, and features the hit single ''Empire State of Mind (Part II) Broken Down''.'),
(92, '25', 'Adele', 'Pop', 2015, 'XL', 'Adele''s 25 is a critically acclaimed album that blends pop, soul, and R&B, and features the hit single ''Hello''.'),
(93, '21', 'Adele', 'Pop', 2011, 'XL', 'Adele''s 21 is a critically acclaimed album that blends pop, soul, and R&B, and features the hit single ''Rolling in the Deep''.'),
(94, '19', 'Adele', 'Pop', 2008, 'XL', 'Adele''s 19 is a critically acclaimed album that blends pop, soul, and jazz, and features the hit single ''Chasing Pavements''.'),
(95, 'Lemonade', 'Beyoncé', 'R&B', 2016, 'Parkwood', 'Beyoncé''s Lemonade is a critically acclaimed album that blends R&B, hip hop, and rock, and explores themes of love, betrayal, and empowerment.'),
(96, '4', 'Beyoncé', 'R&B', 2011, 'Parkwood', 'Beyoncé''s 4 is a critically acclaimed album that blends R&B, pop, and soul, and features the hit single ''Run the World (Girls)''.'),
(97, 'Dangerously in Love', 'Beyoncé', 'R&B', 2003, 'Columbia', 'Beyoncé''s Dangerously in Love is a critically acclaimed album that blends R&B, pop, and hip hop, and features the hit single ''Crazy in Love''.'),
(98, 'B''Day', 'Beyoncé', 'R&B', 2006, 'Columbia', 'Beyoncé''s B''Day is a critically acclaimed album that blends R&B, pop, and hip hop, and features the hit single ''Irreplaceable''.'),
(99, 'I Am... Sasha Fierce', 'Beyoncé', 'R&B', 2008, 'Columbia', 'Beyoncé''s I Am... Sasha Fierce is a critically acclaimed album that blends R&B, pop, and dance, and features the hit single ''Single Ladies (Put a Ring on It)''.'),
(100, 'Beyoncé', 'Beyoncé', 'R&B', 2013, 'Parkwood', 'Beyoncé''s self-titled album is a critically acclaimed visual album that blends R&B, pop, and hip hop, and features the hit single ''Drunk in Love''.'),
(101, 'The Emancipation of Mimi', 'Mariah Carey', 'R&B', 2005, 'Island', 'Mariah Carey''s The Emancipation of Mimi is a critically acclaimed album that blends R&B, pop, and hip hop, and features the hit single ''We Belong Together''.'),
(102, 'Daydream', 'Mariah Carey', 'R&B', 1995, 'Columbia', 'Mariah Carey''s Daydream is a critically acclaimed album that blends R&B, pop, and hip hop, and features the hit single ''Fantasy''.'),
(103, 'Butterfly', 'Mariah Carey', 'R&B', 1997, 'Columbia', 'Mariah Carey''s Butterfly is a critically acclaimed album that blends R&B, pop, and hip hop, and features the hit single ''Honey''.'),
(104, 'Music Box', 'Mariah Carey', 'R&B', 1993, 'Columbia', 'Mariah Carey''s Music Box is a critically acclaimed album that blends R&B, pop, and soul, and features the hit single ''Hero''.'),
(105, 'Rainbow', 'Mariah Carey', 'R&B', 1999, 'Columbia', 'Mariah Carey''s Rainbow is a critically acclaimed album that blends R&B, pop, and hip hop, and features the hit single ''Heartbreaker''.');
